apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular
  labels:
    app: angular
spec:
  selector:
    matchLabels:
      app: angular
  replicas: 2
  template:
    metadata:
      labels:
        app: angular
    spec:
      containers:
        - name: angular
          image: jonathanlareau/simple-angular-hello:latest
          ports:
            - name: angular-service
              containerPort: 4200

---
apiVersion: v1
kind: Service
metadata:
  name: angular-service
spec:
  selector:
    app: angular
  ports:
    - name: http
      port: 4200
      nodePort: 30080
  type: NodePort