apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  labels:
    app: client
spec:
  selector:
    matchLabels:
      app: client
  replicas: 2
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: api-service
          image: jonathanlareau/simple-client-go:latest
          ports:
            - name: client
              containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: client
  ports:
    - port: 8080
      targetPort: 8080